from datetime import datetime
from app import db
from werkzeug.security import generate_password_hash, check_password_hash

class User(db.Model):
    """用户表"""
    __tablename__ = 'users'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(50), unique=True, nullable=False, index=True)
    password_hash = db.Column(db.String(255), nullable=False)
    real_name = db.Column(db.String(50), nullable=False)
    role = db.Column(db.Enum('admin', 'regional_manager', 'shop_manager', name='user_role'), nullable=False)
    shop_id = db.Column(db.Integer, db.ForeignKey('shops.id'), nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    
    # 关系
    shop = db.relationship('Shop', foreign_keys=[shop_id], backref='staff_members')
    created_work_orders = db.relationship('WorkOrder', foreign_keys='WorkOrder.creator_id', backref='creator')
    assigned_work_orders = db.relationship('WorkOrder', foreign_keys='WorkOrder.assignee_id', backref='assignee')
    comments = db.relationship('TaskComment', backref='author', lazy='dynamic')
    
    def set_password(self, password):
        """设置密码"""
        self.password_hash = generate_password_hash(password)
    
    def check_password(self, password):
        """验证密码"""
        return check_password_hash(self.password_hash, password)
    
    def to_dict(self):
        """转换为字典"""
        return {
            'id': self.id,
            'username': self.username,
            'real_name': self.real_name,
            'role': self.role,
            'shop_id': self.shop_id,
            'shop_name': self.shop.name if self.shop else None,
            'created_at': self.created_at.isoformat() if self.created_at else None
        }


class Shop(db.Model):
    """门店表"""
    __tablename__ = 'shops'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(100), nullable=False, unique=True)
    address = db.Column(db.String(255))
    regional_manager_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    
    # 关系
    regional_manager = db.relationship('User', foreign_keys=[regional_manager_id], backref='managed_shops')
    work_orders = db.relationship('WorkOrder', backref='shop', lazy='dynamic')
    auto_tasks = db.relationship('AutoGeneratedTask', backref='shop', lazy='dynamic')
    
    def to_dict(self):
        """转换为字典"""
        return {
            'id': self.id,
            'name': self.name,
            'address': self.address,
            'regional_manager_id': self.regional_manager_id,
            'regional_manager_name': self.regional_manager.real_name if self.regional_manager else None,
            'created_at': self.created_at.isoformat() if self.created_at else None
        }


class DictTaskType(db.Model):
    """任务类型字典表（仅总部管理员可维护）"""
    __tablename__ = 'dict_task_type'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    type_name = db.Column(db.String(50), unique=True, nullable=False)
    color = db.Column(db.String(7))  # 颜色代码，如 #FF0000
    
    work_orders = db.relationship('WorkOrder', backref='task_type', lazy='dynamic')
    
    def to_dict(self):
        return {
            'id': self.id,
            'type_name': self.type_name,
            'color': self.color
        }


class DictPriority(db.Model):
    """优先级字典表"""
    __tablename__ = 'dict_priority'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    priority_name = db.Column(db.String(20), unique=True, nullable=False)
    color = db.Column(db.String(7))
    sort_order = db.Column(db.Integer, default=0)
    
    work_orders = db.relationship('WorkOrder', backref='priority', lazy='dynamic')
    
    def to_dict(self):
        return {
            'id': self.id,
            'priority_name': self.priority_name,
            'color': self.color,
            'sort_order': self.sort_order
        }


class DictStatus(db.Model):
    """状态字典表"""
    __tablename__ = 'dict_status'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    status_name = db.Column(db.String(20), unique=True, nullable=False)
    color = db.Column(db.String(7))
    
    work_orders = db.relationship('WorkOrder', backref='status', lazy='dynamic')
    
    def to_dict(self):
        return {
            'id': self.id,
            'status_name': self.status_name,
            'color': self.color
        }


class WorkOrder(db.Model):
    """工单任务主表"""
    __tablename__ = 'work_orders'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    title = db.Column(db.String(255), nullable=False)
    description = db.Column(db.Text)
    type_id = db.Column(db.Integer, db.ForeignKey('dict_task_type.id'), nullable=False)
    priority_id = db.Column(db.Integer, db.ForeignKey('dict_priority.id'), nullable=False)
    status_id = db.Column(db.Integer, db.ForeignKey('dict_status.id'), nullable=False)
    creator_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    assignee_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    shop_id = db.Column(db.Integer, db.ForeignKey('shops.id'), nullable=False)
    due_date = db.Column(db.DateTime, nullable=False)
    completion_notes = db.Column(db.Text)
    completion_progress = db.Column(db.SmallInteger, default=0)  # 0-100
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # 关系
    comments = db.relationship('TaskComment', backref='work_order', lazy='dynamic', cascade='all, delete-orphan')
    attachments = db.relationship('TaskAttachment', backref='work_order', lazy='dynamic', cascade='all, delete-orphan')
    
    def to_dict(self, include_details=False):
        """转换为字典"""
        data = {
            'id': self.id,
            'title': self.title,
            'description': self.description,
            'type': self.task_type.to_dict() if self.task_type else None,
            'priority': self.priority.to_dict() if self.priority else None,
            'status': self.status.to_dict() if self.status else None,
            'creator': {
                'id': self.creator.id,
                'real_name': self.creator.real_name
            } if self.creator else None,
            'assignee': {
                'id': self.assignee.id,
                'real_name': self.assignee.real_name
            } if self.assignee else None,
            'shop': self.shop.to_dict() if self.shop else None,
            'due_date': self.due_date.isoformat() if self.due_date else None,
            'completion_progress': self.completion_progress,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'updated_at': self.updated_at.isoformat() if self.updated_at else None,
        }
        
        if include_details:
            data['completion_notes'] = self.completion_notes
            data['comments'] = [c.to_dict() for c in self.comments.order_by(TaskComment.created_at.desc()).all()]
            data['attachments'] = [a.to_dict() for a in self.attachments.all()]
        
        return data


class TaskComment(db.Model):
    """任务评论/沟通表"""
    __tablename__ = 'task_comments'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    work_order_id = db.Column(db.Integer, db.ForeignKey('work_orders.id'), nullable=False)
    author_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    content = db.Column(db.Text, nullable=False)
    attachment_url = db.Column(db.String(500))
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    
    def to_dict(self):
        return {
            'id': self.id,
            'work_order_id': self.work_order_id,
            'author': {
                'id': self.author.id,
                'real_name': self.author.real_name
            } if self.author else None,
            'content': self.content,
            'attachment_url': self.attachment_url,
            'created_at': self.created_at.isoformat() if self.created_at else None
        }


class TaskAttachment(db.Model):
    """任务附件表"""
    __tablename__ = 'task_attachments'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    work_order_id = db.Column(db.Integer, db.ForeignKey('work_orders.id'), nullable=False)
    file_name = db.Column(db.String(255), nullable=False)
    file_url = db.Column(db.String(500), nullable=False)
    file_type = db.Column(db.String(50))
    uploaded_by = db.Column(db.Integer, db.ForeignKey('users.id'))
    uploaded_at = db.Column(db.DateTime, default=datetime.utcnow)
    
    uploader = db.relationship('User', backref='uploaded_attachments')
    
    def to_dict(self):
        return {
            'id': self.id,
            'file_name': self.file_name,
            'file_url': self.file_url,
            'file_type': self.file_type,
            'uploaded_by': self.uploader.real_name if self.uploader else None,
            'uploaded_at': self.uploaded_at.isoformat() if self.uploaded_at else None
        }


class RoutineTaskTemplate(db.Model):
    """标准清洁任务模板表（仅总部管理员可维护）"""
    __tablename__ = 'routine_task_templates'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    task_name = db.Column(db.String(255), nullable=False)
    description = db.Column(db.Text)
    frequency = db.Column(db.Enum('daily', 'weekly', 'monthly', name='task_frequency'), nullable=False)
    checklist_json = db.Column(db.JSON)  # 检查清单JSON数组
    is_active = db.Column(db.Boolean, default=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    
    # 关系
    auto_tasks = db.relationship('AutoGeneratedTask', backref='template', lazy='dynamic')
    
    def to_dict(self):
        return {
            'id': self.id,
            'task_name': self.task_name,
            'description': self.description,
            'frequency': self.frequency,
            'checklist': self.checklist_json,
            'is_active': self.is_active,
            'created_at': self.created_at.isoformat() if self.created_at else None
        }


class AutoGeneratedTask(db.Model):
    """自动生成任务表"""
    __tablename__ = 'auto_generated_tasks'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    template_id = db.Column(db.Integer, db.ForeignKey('routine_task_templates.id'), nullable=False)
    shop_id = db.Column(db.Integer, db.ForeignKey('shops.id'), nullable=False)
    due_date = db.Column(db.Date, nullable=False)
    is_completed = db.Column(db.Boolean, default=False)
    completed_at = db.Column(db.DateTime)
    completed_by = db.Column(db.Integer, db.ForeignKey('users.id'))
    checklist_status = db.Column(db.JSON)  # 记录每个检查项的完成状态
    
    completer = db.relationship('User', backref='completed_routine_tasks')
    
    def to_dict(self):
        return {
            'id': self.id,
            'template': self.template.to_dict() if self.template else None,
            'shop': self.shop.to_dict() if self.shop else None,
            'due_date': self.due_date.isoformat() if self.due_date else None,
            'is_completed': self.is_completed,
            'completed_at': self.completed_at.isoformat() if self.completed_at else None,
            'completed_by': self.completer.real_name if self.completer else None,
            'checklist_status': self.checklist_status
        }


class TrainingCategory(db.Model):
    """培训分类表"""
    __tablename__ = 'training_categories'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(100), nullable=False)
    parent_id = db.Column(db.Integer, db.ForeignKey('training_categories.id'), nullable=True)
    type = db.Column(db.Enum('product', 'service', 'operation', name='training_type'), nullable=False)
    sort_order = db.Column(db.Integer, default=0)
    
    # 自关联
    children = db.relationship('TrainingCategory', backref=db.backref('parent', remote_side=[id]))
    courses = db.relationship('TrainingCourse', backref='category', lazy='dynamic')
    
    def to_dict(self, include_children=False):
        data = {
            'id': self.id,
            'name': self.name,
            'parent_id': self.parent_id,
            'type': self.type,
            'sort_order': self.sort_order
        }
        if include_children:
            data['children'] = [c.to_dict() for c in self.children]
        return data


class TrainingCourse(db.Model):
    """培训课程表"""
    __tablename__ = 'training_courses'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    title = db.Column(db.String(255), nullable=False)
    description = db.Column(db.Text)
    category_id = db.Column(db.Integer, db.ForeignKey('training_categories.id'), nullable=False)
    content_type = db.Column(db.Enum('text', 'pdf', 'video', name='content_type'), nullable=False)
    content_url = db.Column(db.String(500))
    content_text = db.Column(db.Text)
    has_exam = db.Column(db.Boolean, default=False)
    is_published = db.Column(db.Boolean, default=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    
    # 关系
    exam_questions = db.relationship('ExamQuestion', backref='course', lazy='dynamic')
    learning_records = db.relationship('LearningRecord', backref='course', lazy='dynamic')
    
    def to_dict(self):
        return {
            'id': self.id,
            'title': self.title,
            'description': self.description,
            'category': self.category.to_dict() if self.category else None,
            'content_type': self.content_type,
            'content_url': self.content_url,
            'content_text': self.content_text,
            'has_exam': self.has_exam,
            'is_published': self.is_published,
            'created_at': self.created_at.isoformat() if self.created_at else None
        }


class ExamQuestion(db.Model):
    """考试题库表"""
    __tablename__ = 'exam_questions'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    course_id = db.Column(db.Integer, db.ForeignKey('training_courses.id'), nullable=False)
    question_text = db.Column(db.Text, nullable=False)
    question_type = db.Column(db.Enum('single_choice', 'multiple_choice', 'true_false', name='question_type'), nullable=False)
    options = db.Column(db.JSON)  # 选项数组
    correct_answer = db.Column(db.String(255), nullable=False)  # 正确答案
    
    def to_dict(self):
        return {
            'id': self.id,
            'question_text': self.question_text,
            'question_type': self.question_type,
            'options': self.options,
            'correct_answer': self.correct_answer
        }


class LearningRecord(db.Model):
    """学习记录表"""
    __tablename__ = 'learning_records'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    course_id = db.Column(db.Integer, db.ForeignKey('training_courses.id'), nullable=False)
    completed = db.Column(db.Boolean, default=False)
    exam_score = db.Column(db.Integer)  # 考试分数
    exam_passed = db.Column(db.Boolean, default=False)
    started_at = db.Column(db.DateTime, default=datetime.utcnow)
    completed_at = db.Column(db.DateTime)
    
    learner = db.relationship('User', backref='learning_records')
    
    def to_dict(self):
        return {
            'id': self.id,
            'user_id': self.user_id,
            'course': self.course.to_dict() if self.course else None,
            'completed': self.completed,
            'exam_score': self.exam_score,
            'exam_passed': self.exam_passed,
            'started_at': self.started_at.isoformat() if self.started_at else None,
            'completed_at': self.completed_at.isoformat() if self.completed_at else None
        }

