from datetime import datetime
from app import db
from werkzeug.security import generate_password_hash, check_password_hash

class User(db.Model):
    """用户表"""
    __tablename__ = 'users'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(50), unique=True, nullable=False, index=True)
    password_hash = db.Column(db.String(255), nullable=False)
    real_name = db.Column(db.String(50), nullable=False)
    role = db.Column(db.Enum('admin', 'regional_manager', 'shop_manager', 'delivery_operation', name='user_role'), nullable=False)
    shop_id = db.Column(db.Integer, db.ForeignKey('shops.id'), nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    
    # 关系
    shop = db.relationship('Shop', foreign_keys=[shop_id], backref='staff_members')
    created_work_orders = db.relationship('WorkOrder', foreign_keys='WorkOrder.creator_id', backref='creator')
    assigned_work_orders = db.relationship('WorkOrder', foreign_keys='WorkOrder.assignee_id', backref='assignee')
    comments = db.relationship('TaskComment', backref='author', lazy='dynamic')
    
    def set_password(self, password):
        """设置密码"""
        self.password_hash = generate_password_hash(password)
    
    def check_password(self, password):
        """验证密码"""
        return check_password_hash(self.password_hash, password)
    
    def to_dict(self):
        """转换为字典"""
        return {
            'id': self.id,
            'username': self.username,
            'real_name': self.real_name,
            'role': self.role,
            'shop_id': self.shop_id,
            'shop_name': self.shop.name if self.shop else None,
            'created_at': self.created_at.isoformat() if self.created_at else None
        }


class Shop(db.Model):
    """门店表"""
    __tablename__ = 'shops'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(100), nullable=False, unique=True)
    address = db.Column(db.String(255))
    regional_manager_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    manager_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    
    # 关系
    regional_manager = db.relationship('User', foreign_keys=[regional_manager_id], backref='managed_shops')
    manager = db.relationship('User', foreign_keys=[manager_id], backref='managed_shop')
    work_orders = db.relationship('WorkOrder', backref='shop', lazy='dynamic')
    auto_tasks = db.relationship('AutoGeneratedTask', backref='shop', lazy='dynamic')
    
    def to_dict(self):
        """转换为字典"""
        return {
            'id': self.id,
            'name': self.name,
            'address': self.address,
            'regional_manager_id': self.regional_manager_id,
            'regional_manager': {
                'id': self.regional_manager.id,
                'real_name': self.regional_manager.real_name,
                'username': self.regional_manager.username
            } if self.regional_manager else None,
            'manager_id': self.manager_id,
            'manager': {
                'id': self.manager.id,
                'real_name': self.manager.real_name,
                'username': self.manager.username
            } if self.manager else None,
            'created_at': self.created_at.isoformat() if self.created_at else None
        }


class DictTaskType(db.Model):
    """任务类型字典表（仅总部管理员可维护）"""
    __tablename__ = 'dict_task_type'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    type_name = db.Column(db.String(50), unique=True, nullable=False)
    color = db.Column(db.String(7))  # 颜色代码，如 #FF0000
    
    work_orders = db.relationship('WorkOrder', backref='task_type', lazy='dynamic')
    
    def to_dict(self):
        return {
            'id': self.id,
            'type_name': self.type_name,
            'color': self.color
        }


class DictPriority(db.Model):
    """优先级字典表"""
    __tablename__ = 'dict_priority'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    priority_name = db.Column(db.String(20), unique=True, nullable=False)
    color = db.Column(db.String(7))
    sort_order = db.Column(db.Integer, default=0)
    
    work_orders = db.relationship('WorkOrder', backref='priority', lazy='dynamic')
    
    def to_dict(self):
        return {
            'id': self.id,
            'priority_name': self.priority_name,
            'color': self.color,
            'sort_order': self.sort_order
        }


class DictStatus(db.Model):
    """状态字典表"""
    __tablename__ = 'dict_status'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    status_name = db.Column(db.String(20), unique=True, nullable=False)
    color = db.Column(db.String(7))
    
    work_orders = db.relationship('WorkOrder', backref='status', lazy='dynamic')
    
    def to_dict(self):
        return {
            'id': self.id,
            'status_name': self.status_name,
            'color': self.color
        }


class WorkOrder(db.Model):
    """工单任务主表"""
    __tablename__ = 'work_orders'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    title = db.Column(db.String(255), nullable=False)
    description = db.Column(db.Text)
    type_id = db.Column(db.Integer, db.ForeignKey('dict_task_type.id'), nullable=False)
    priority_id = db.Column(db.Integer, db.ForeignKey('dict_priority.id'), nullable=False)
    status_id = db.Column(db.Integer, db.ForeignKey('dict_status.id'), nullable=False)
    creator_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    assignee_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    shop_id = db.Column(db.Integer, db.ForeignKey('shops.id'), nullable=False)
    due_date = db.Column(db.DateTime, nullable=False)
    completion_notes = db.Column(db.Text)
    completion_progress = db.Column(db.SmallInteger, default=0)  # 0-100
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # 关系
    comments = db.relationship('TaskComment', backref='work_order', lazy='dynamic', cascade='all, delete-orphan')
    attachments = db.relationship('TaskAttachment', backref='work_order', lazy='dynamic', cascade='all, delete-orphan')
    
    def to_dict(self, include_details=False):
        """转换为字典"""
        data = {
            'id': self.id,
            'title': self.title,
            'description': self.description,
            'type': self.task_type.to_dict() if self.task_type else None,
            'priority': self.priority.to_dict() if self.priority else None,
            'status': self.status.to_dict() if self.status else None,
            'creator': {
                'id': self.creator.id,
                'real_name': self.creator.real_name
            } if self.creator else None,
            'assignee': {
                'id': self.assignee.id,
                'real_name': self.assignee.real_name
            } if self.assignee else None,
            'shop': self.shop.to_dict() if self.shop else None,
            'due_date': self.due_date.isoformat() if self.due_date else None,
            'completion_progress': self.completion_progress,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'updated_at': self.updated_at.isoformat() if self.updated_at else None,
        }
        
        if include_details:
            data['completion_notes'] = self.completion_notes
            data['comments'] = [c.to_dict() for c in self.comments.order_by(TaskComment.created_at.desc()).all()]
            data['attachments'] = [a.to_dict() for a in self.attachments.all()]
        
        return data


class TaskComment(db.Model):
    """任务评论/沟通表"""
    __tablename__ = 'task_comments'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    work_order_id = db.Column(db.Integer, db.ForeignKey('work_orders.id'), nullable=False)
    author_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    content = db.Column(db.Text, nullable=False)
    attachment_url = db.Column(db.String(500))
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    
    def to_dict(self):
        return {
            'id': self.id,
            'work_order_id': self.work_order_id,
            'author': {
                'id': self.author.id,
                'real_name': self.author.real_name
            } if self.author else None,
            'content': self.content,
            'attachment_url': self.attachment_url,
            'created_at': self.created_at.isoformat() if self.created_at else None
        }


class TaskAttachment(db.Model):
    """任务附件表"""
    __tablename__ = 'task_attachments'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    work_order_id = db.Column(db.Integer, db.ForeignKey('work_orders.id'), nullable=False)
    file_name = db.Column(db.String(255), nullable=False)
    file_url = db.Column(db.String(500), nullable=False)
    file_type = db.Column(db.String(50))
    uploaded_by = db.Column(db.Integer, db.ForeignKey('users.id'))
    uploaded_at = db.Column(db.DateTime, default=datetime.utcnow)
    
    uploader = db.relationship('User', backref='uploaded_attachments')
    
    def to_dict(self):
        return {
            'id': self.id,
            'file_name': self.file_name,
            'file_url': self.file_url,
            'file_type': self.file_type,
            'uploaded_by': self.uploader.real_name if self.uploader else None,
            'uploaded_at': self.uploaded_at.isoformat() if self.uploaded_at else None
        }


class RoutineTaskTemplate(db.Model):
    """标准清洁任务模板表（仅总部管理员可维护）"""
    __tablename__ = 'routine_task_templates'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    task_name = db.Column(db.String(255), nullable=False)
    description = db.Column(db.Text)
    frequency = db.Column(db.Enum('daily', 'weekly', 'monthly', name='task_frequency'), nullable=False)
    checklist_json = db.Column(db.JSON)  # 检查清单JSON数组
    is_active = db.Column(db.Boolean, default=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    
    # 关系
    auto_tasks = db.relationship('AutoGeneratedTask', backref='template', lazy='dynamic')
    
    def to_dict(self):
        return {
            'id': self.id,
            'task_name': self.task_name,
            'description': self.description,
            'frequency': self.frequency,
            'checklist': self.checklist_json,
            'is_active': self.is_active,
            'created_at': self.created_at.isoformat() if self.created_at else None
        }


class AutoGeneratedTask(db.Model):
    """自动生成任务表"""
    __tablename__ = 'auto_generated_tasks'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    template_id = db.Column(db.Integer, db.ForeignKey('routine_task_templates.id'), nullable=False)
    shop_id = db.Column(db.Integer, db.ForeignKey('shops.id'), nullable=False)
    due_date = db.Column(db.Date, nullable=False)
    is_completed = db.Column(db.Boolean, default=False)
    completed_at = db.Column(db.DateTime)
    completed_by = db.Column(db.Integer, db.ForeignKey('users.id'))
    checklist_status = db.Column(db.JSON)  # 记录每个检查项的完成状态
    
    completer = db.relationship('User', backref='completed_routine_tasks')
    
    def to_dict(self):
        return {
            'id': self.id,
            'template': self.template.to_dict() if self.template else None,
            'shop': self.shop.to_dict() if self.shop else None,
            'due_date': self.due_date.isoformat() if self.due_date else None,
            'is_completed': self.is_completed,
            'completed_at': self.completed_at.isoformat() if self.completed_at else None,
            'completed_by': self.completer.real_name if self.completer else None,
            'checklist_status': self.checklist_status
        }


class TrainingCategory(db.Model):
    """培训分类表"""
    __tablename__ = 'training_categories'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(100), nullable=False)
    parent_id = db.Column(db.Integer, db.ForeignKey('training_categories.id'), nullable=True)
    type = db.Column(db.Enum('product', 'service', 'operation', name='training_type'), nullable=False)
    sort_order = db.Column(db.Integer, default=0)
    
    # 自关联
    children = db.relationship('TrainingCategory', backref=db.backref('parent', remote_side=[id]))
    courses = db.relationship('TrainingCourse', backref='category', lazy='dynamic')
    
    def to_dict(self, include_children=False):
        data = {
            'id': self.id,
            'name': self.name,
            'parent_id': self.parent_id,
            'type': self.type,
            'sort_order': self.sort_order
        }
        if include_children:
            data['children'] = [c.to_dict() for c in self.children]
        return data


class TrainingCourse(db.Model):
    """培训课程表 - 视频+文档+考试一体化"""
    __tablename__ = 'training_courses'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    title = db.Column(db.String(255), nullable=False)
    description = db.Column(db.Text)
    category_id = db.Column(db.Integer, db.ForeignKey('training_categories.id'), nullable=False)
    video_url = db.Column(db.String(500))  # 视频地址（可选）
    document_content = db.Column(db.Text)  # 富文本文档内容
    has_exam = db.Column(db.Boolean, default=False)
    is_published = db.Column(db.Boolean, default=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    
    # 关系
    exam_questions = db.relationship('ExamQuestion', backref='course', lazy='dynamic')
    learning_records = db.relationship('LearningRecord', backref='course', lazy='dynamic')
    exam_submissions = db.relationship('ExamSubmission', backref='course', lazy='dynamic')
    
    def to_dict(self, include_questions=False):
        data = {
            'id': self.id,
            'title': self.title,
            'description': self.description,
            'category': self.category.to_dict() if self.category else None,
            'video_url': self.video_url,
            'document_content': self.document_content,
            'has_exam': self.has_exam,
            'is_published': self.is_published,
            'created_at': self.created_at.isoformat() if self.created_at else None
        }
        if include_questions:
            data['exam_questions'] = [q.to_dict() for q in self.exam_questions.all()]
        return data


class ExamQuestion(db.Model):
    """考试题库表 - 支持客观题和主观题"""
    __tablename__ = 'exam_questions'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    course_id = db.Column(db.Integer, db.ForeignKey('training_courses.id'), nullable=False)
    question_text = db.Column(db.Text, nullable=False)
    question_type = db.Column(db.Enum('single_choice', 'multiple_choice', 'true_false', 'subjective', name='question_type'), nullable=False)
    options = db.Column(db.JSON)  # 选项数组（客观题使用）
    correct_answer = db.Column(db.String(255))  # 正确答案（客观题使用，主观题为空）
    is_subjective = db.Column(db.Boolean, default=False)  # 是否为主观题
    score = db.Column(db.Integer, default=10)  # 题目分值
    sort_order = db.Column(db.Integer, default=0)  # 排序
    
    def to_dict(self, include_answer=False):
        """
        转换为字典
        include_answer: 是否包含答案（考试时不返回答案）
        """
        data = {
            'id': self.id,
            'question_text': self.question_text,
            'question_type': self.question_type,
            'options': self.options,
            'is_subjective': self.is_subjective,
            'score': self.score,
            'sort_order': self.sort_order
        }
        if include_answer and not self.is_subjective:
            data['correct_answer'] = self.correct_answer
        return data


class LearningRecord(db.Model):
    """学习记录表 - 记录视频进度和学习状态"""
    __tablename__ = 'learning_records'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    course_id = db.Column(db.Integer, db.ForeignKey('training_courses.id'), nullable=False)
    video_progress = db.Column(db.Integer, default=0)  # 视频观看进度（秒）
    document_read = db.Column(db.Boolean, default=False)  # 是否已阅读文档
    completed = db.Column(db.Boolean, default=False)
    exam_score = db.Column(db.Integer)  # 考试分数（已废弃，改用ExamSubmission）
    exam_passed = db.Column(db.Boolean, default=False)
    started_at = db.Column(db.DateTime, default=datetime.utcnow)
    completed_at = db.Column(db.DateTime)
    
    learner = db.relationship('User', backref='learning_records')
    
    def to_dict(self):
        return {
            'id': self.id,
            'user_id': self.user_id,
            'course': self.course.to_dict() if self.course else None,
            'video_progress': self.video_progress,
            'document_read': self.document_read,
            'completed': self.completed,
            'exam_score': self.exam_score,
            'exam_passed': self.exam_passed,
            'started_at': self.started_at.isoformat() if self.started_at else None,
            'completed_at': self.completed_at.isoformat() if self.completed_at else None
        }


class ExamSubmission(db.Model):
    """考试提交表 - 记录考试答案和评分"""
    __tablename__ = 'exam_submissions'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    course_id = db.Column(db.Integer, db.ForeignKey('training_courses.id'), nullable=False)
    answers = db.Column(db.JSON, nullable=False)  # 格式: {"question_id": "answer", ...}
    objective_score = db.Column(db.Integer, default=0)  # 客观题得分（自动判分）
    subjective_score = db.Column(db.Integer, default=0)  # 主观题得分（管理员评分）
    total_score = db.Column(db.Integer, default=0)  # 总分
    status = db.Column(db.Enum('pending_review', 'passed', 'failed', name='exam_status'), default='pending_review')
    reviewed_by = db.Column(db.Integer, db.ForeignKey('users.id'))  # 审核人
    reviewed_at = db.Column(db.DateTime)  # 审核时间
    feedback = db.Column(db.Text)  # 审核反馈
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    
    # 关系
    student = db.relationship('User', foreign_keys=[user_id], backref='exam_submissions')
    reviewer = db.relationship('User', foreign_keys=[reviewed_by], backref='reviewed_exams')
    
    def to_dict(self, include_answers=True):
        data = {
            'id': self.id,
            'user_id': self.user_id,
            'student_name': self.student.real_name if self.student else None,
            'course_id': self.course_id,
            'course_name': self.course.title if self.course else None,
            'objective_score': self.objective_score,
            'subjective_score': self.subjective_score,
            'total_score': self.total_score,
            'status': self.status,
            'reviewed_by': self.reviewed_by,
            'reviewer_name': self.reviewer.real_name if self.reviewer else None,
            'reviewed_at': self.reviewed_at.isoformat() if self.reviewed_at else None,
            'feedback': self.feedback,
            'created_at': self.created_at.isoformat() if self.created_at else None
        }
        if include_answers:
            data['answers'] = self.answers
        return data


class ActivityLog(db.Model):
    """活动日志表 - 记录系统中的各种操作"""
    __tablename__ = 'activity_logs'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    action_type = db.Column(db.Enum(
        'work_order_created',      # 工单创建
        'work_order_status_changed',  # 工单状态变更
        'work_order_assigned',     # 工单分配
        'work_order_comment',      # 工单评论
        'work_order_image_added',  # 工单图片添加
        name='activity_type'
    ), nullable=False)
    work_order_id = db.Column(db.Integer, db.ForeignKey('work_orders.id'), nullable=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)  # 执行操作的用户
    target_user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=True)  # 目标用户（如分配给谁）
    old_value = db.Column(db.String(100), nullable=True)  # 旧值（如状态变更前）
    new_value = db.Column(db.String(100), nullable=True)  # 新值（如状态变更后）
    comment = db.Column(db.Text, nullable=True)  # 备注/评论内容
    created_at = db.Column(db.DateTime, default=datetime.utcnow, index=True)
    
    # 关系
    work_order = db.relationship('WorkOrder', backref='activity_logs')
    user = db.relationship('User', foreign_keys=[user_id], backref='actions')
    target_user = db.relationship('User', foreign_keys=[target_user_id])
    
    def to_dict(self):
        """转换为字典"""
        # 构建活动描述
        description = self._build_description()
        
        return {
            'id': self.id,
            'action_type': self.action_type,
            'work_order_id': self.work_order_id,
            'work_order_title': self.work_order.title if self.work_order else None,
            'user_id': self.user_id,
            'user_name': self.user.real_name if self.user else None,
            'target_user_id': self.target_user_id,
            'target_user_name': self.target_user.real_name if self.target_user else None,
            'old_value': self.old_value,
            'new_value': self.new_value,
            'comment': self.comment,
            'description': description,
            'created_at': self.created_at.isoformat() if self.created_at else None
        }
    
    def _build_description(self):
        """构建活动描述文本"""
        user_name = self.user.real_name if self.user else '未知用户'
        
        if self.action_type == 'work_order_created':
            return f'{user_name} 创建了工单'
        elif self.action_type == 'work_order_status_changed':
            return f'{user_name} 将状态从 {self.old_value} 改为 {self.new_value}'
        elif self.action_type == 'work_order_assigned':
            target_name = self.target_user.real_name if self.target_user else '未知用户'
            return f'{user_name} 将工单分配给 {target_name}'
        elif self.action_type == 'work_order_comment':
            return f'{user_name} 添加了评论'
        elif self.action_type == 'work_order_image_added':
            return f'{user_name} 上传了图片'
        else:
            return f'{user_name} 执行了操作'


class ElemeStoreDailyData(db.Model):
    """饿了么门店每日数据表"""
    __tablename__ = 'eleme_store_daily_data'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    
    # 基础信息
    data_date = db.Column(db.Date, nullable=False, index=True)
    store_name = db.Column(db.String(200), nullable=False)
    store_id = db.Column(db.String(50), index=True)
    province = db.Column(db.String(50))
    city = db.Column(db.String(50), index=True)
    district = db.Column(db.String(50))
    address = db.Column(db.String(500))
    first_open_time = db.Column(db.DateTime)
    is_direct = db.Column(db.String(10))
    
    # 运营时长
    business_hours = db.Column(db.String(50))
    peak_hours = db.Column(db.String(50))
    abnormal_close_hours = db.Column(db.String(50))
    is_valid_store = db.Column(db.String(10))
    
    # 订单财务（核心指标）
    valid_orders = db.Column(db.Integer, default=0)
    invalid_orders = db.Column(db.Integer, default=0)
    merchant_invalid_orders = db.Column(db.Integer, default=0)
    income = db.Column(db.Numeric(10, 2), default=0)
    packaging_fee = db.Column(db.Numeric(10, 2), default=0)
    platform_service_fee = db.Column(db.Numeric(10, 2), default=0)
    delivery_subsidy = db.Column(db.Numeric(10, 2), default=0)
    fulfillment_service_fee = db.Column(db.Numeric(10, 2), default=0)
    refund_fee = db.Column(db.Numeric(10, 2), default=0)
    customer_payment_total = db.Column(db.Numeric(10, 2), default=0)
    avg_payment_per_order = db.Column(db.Numeric(10, 2), default=0)
    avg_income_per_order = db.Column(db.Numeric(10, 2), default=0)
    
    # 营销漏斗
    exposure_users = db.Column(db.Integer, default=0)
    exposure_new_users = db.Column(db.Integer, default=0)
    exposure_old_users = db.Column(db.Integer, default=0)
    exposure_times = db.Column(db.Integer, default=0)
    visit_users = db.Column(db.Integer, default=0)
    visit_new_users = db.Column(db.Integer, default=0)
    visit_old_users = db.Column(db.Integer, default=0)
    visit_times = db.Column(db.Integer, default=0)
    order_users = db.Column(db.Integer, default=0)
    order_new_users = db.Column(db.Integer, default=0)
    order_old_users = db.Column(db.Integer, default=0)
    order_times = db.Column(db.Integer, default=0)
    visit_conversion_rate = db.Column(db.Numeric(5, 2))
    new_visit_conversion_rate = db.Column(db.Numeric(5, 2))
    old_visit_conversion_rate = db.Column(db.Numeric(5, 2))
    order_conversion_rate = db.Column(db.Numeric(5, 2))
    new_order_conversion_rate = db.Column(db.Numeric(5, 2))
    old_order_conversion_rate = db.Column(db.Numeric(5, 2))
    
    # 商品运营
    online_products = db.Column(db.Integer, default=0)
    sold_products = db.Column(db.Integer, default=0)
    out_of_stock_products = db.Column(db.Integer, default=0)
    new_products = db.Column(db.Integer, default=0)
    promotion_products = db.Column(db.Integer, default=0)
    discount_orders = db.Column(db.Integer, default=0)
    repurchase_7d_users = db.Column(db.Integer, default=0)
    repurchase_7d_rate = db.Column(db.Numeric(5, 2))
    repurchase_30d_users = db.Column(db.Integer, default=0)
    repurchase_30d_rate = db.Column(db.Numeric(5, 2))
    
    # 服务质量
    bad_review_orders = db.Column(db.Integer, default=0)
    complaint_orders = db.Column(db.Integer, default=0)
    complaint_order_ids = db.Column(db.Text)
    overtime_orders = db.Column(db.Integer, default=0)
    overtime_order_ids = db.Column(db.Text)
    avg_cooking_time = db.Column(db.Numeric(5, 2))
    reject_orders = db.Column(db.Integer, default=0)
    merchant_cancel_orders = db.Column(db.Integer, default=0)
    merchant_cancel_rate = db.Column(db.Numeric(5, 2))
    merchant_refund_orders = db.Column(db.Integer, default=0)
    merchant_refund_rate = db.Column(db.Numeric(5, 2))
    avg_pickup_time = db.Column(db.Numeric(5, 2))
    
    # 评分体系
    store_score = db.Column(db.Numeric(3, 2))
    satisfaction_score = db.Column(db.Numeric(3, 2))
    taste_score = db.Column(db.Numeric(3, 2))
    packaging_score = db.Column(db.Numeric(3, 2))
    
    # 近60日评价
    good_rate_60d = db.Column(db.Numeric(5, 2))
    good_count_60d = db.Column(db.Integer, default=0)
    medium_rate_60d = db.Column(db.Numeric(5, 2))
    medium_count_60d = db.Column(db.Integer, default=0)
    bad_rate_60d = db.Column(db.Numeric(5, 2))
    bad_count_60d = db.Column(db.Integer, default=0)
    quality_rate_60d = db.Column(db.Numeric(5, 2))
    quality_count_60d = db.Column(db.Integer, default=0)
    review_rate_60d = db.Column(db.Numeric(5, 2))
    review_count_60d = db.Column(db.Integer, default=0)
    bad_reply_rate_60d = db.Column(db.Numeric(5, 2))
    
    # 近30日评价
    good_rate_30d = db.Column(db.Numeric(5, 2))
    good_count_30d = db.Column(db.Integer, default=0)
    medium_rate_30d = db.Column(db.Numeric(5, 2))
    medium_count_30d = db.Column(db.Integer, default=0)
    bad_rate_30d = db.Column(db.Numeric(5, 2))
    bad_count_30d = db.Column(db.Integer, default=0)
    quality_rate_30d = db.Column(db.Numeric(5, 2))
    quality_count_30d = db.Column(db.Integer, default=0)
    review_rate_30d = db.Column(db.Numeric(5, 2))
    review_count_30d = db.Column(db.Integer, default=0)
    bad_reply_rate_30d = db.Column(db.Numeric(5, 2))
    
    # 元数据
    import_batch_id = db.Column(db.String(50), index=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    
    def to_dict(self):
        """转换为字典（包含所有90+个字段）"""
        return {
            'id': self.id,
            # 基础信息
            'data_date': self.data_date.isoformat() if self.data_date else None,
            'store_name': self.store_name,
            'store_id': self.store_id,
            'province': self.province,
            'city': self.city,
            'district': self.district,
            'address': self.address,
            'first_open_time': self.first_open_time.isoformat() if self.first_open_time else None,
            'is_direct': self.is_direct,
            
            # 运营时长
            'business_hours': self.business_hours,
            'peak_hours': self.peak_hours,
            'abnormal_close_hours': self.abnormal_close_hours,
            'is_valid_store': self.is_valid_store,
            
            # 订单财务
            'valid_orders': self.valid_orders,
            'invalid_orders': self.invalid_orders,
            'merchant_invalid_orders': self.merchant_invalid_orders,
            'income': float(self.income) if self.income else 0,
            'packaging_fee': float(self.packaging_fee) if self.packaging_fee else 0,
            'platform_service_fee': float(self.platform_service_fee) if self.platform_service_fee else 0,
            'delivery_subsidy': float(self.delivery_subsidy) if self.delivery_subsidy else 0,
            'fulfillment_service_fee': float(self.fulfillment_service_fee) if self.fulfillment_service_fee else 0,
            'refund_fee': float(self.refund_fee) if self.refund_fee else 0,
            'customer_payment_total': float(self.customer_payment_total) if self.customer_payment_total else 0,
            'avg_payment_per_order': float(self.avg_payment_per_order) if self.avg_payment_per_order else 0,
            'avg_income_per_order': float(self.avg_income_per_order) if self.avg_income_per_order else 0,
            
            # 营销漏斗
            'exposure_users': self.exposure_users,
            'exposure_new_users': self.exposure_new_users,
            'exposure_old_users': self.exposure_old_users,
            'exposure_times': self.exposure_times,
            'visit_users': self.visit_users,
            'visit_new_users': self.visit_new_users,
            'visit_old_users': self.visit_old_users,
            'visit_times': self.visit_times,
            'order_users': self.order_users,
            'order_new_users': self.order_new_users,
            'order_old_users': self.order_old_users,
            'order_times': self.order_times,
            'visit_conversion_rate': float(self.visit_conversion_rate) if self.visit_conversion_rate else 0,
            'new_visit_conversion_rate': float(self.new_visit_conversion_rate) if self.new_visit_conversion_rate else 0,
            'old_visit_conversion_rate': float(self.old_visit_conversion_rate) if self.old_visit_conversion_rate else 0,
            'order_conversion_rate': float(self.order_conversion_rate) if self.order_conversion_rate else 0,
            'new_order_conversion_rate': float(self.new_order_conversion_rate) if self.new_order_conversion_rate else 0,
            'old_order_conversion_rate': float(self.old_order_conversion_rate) if self.old_order_conversion_rate else 0,
            
            # 商品运营
            'online_products': self.online_products,
            'sold_products': self.sold_products,
            'out_of_stock_products': self.out_of_stock_products,
            'new_products': self.new_products,
            'promotion_products': self.promotion_products,
            'discount_orders': self.discount_orders,
            'repurchase_7d_users': self.repurchase_7d_users,
            'repurchase_7d_rate': float(self.repurchase_7d_rate) if self.repurchase_7d_rate else 0,
            'repurchase_30d_users': self.repurchase_30d_users,
            'repurchase_30d_rate': float(self.repurchase_30d_rate) if self.repurchase_30d_rate else 0,
            
            # 服务质量
            'bad_review_orders': self.bad_review_orders,
            'complaint_orders': self.complaint_orders,
            'complaint_order_ids': self.complaint_order_ids,
            'overtime_orders': self.overtime_orders,
            'overtime_order_ids': self.overtime_order_ids,
            'avg_cooking_time': float(self.avg_cooking_time) if self.avg_cooking_time else 0,
            'reject_orders': self.reject_orders,
            'merchant_cancel_orders': self.merchant_cancel_orders,
            'merchant_cancel_rate': float(self.merchant_cancel_rate) if self.merchant_cancel_rate else 0,
            'merchant_refund_orders': self.merchant_refund_orders,
            'merchant_refund_rate': float(self.merchant_refund_rate) if self.merchant_refund_rate else 0,
            'avg_pickup_time': float(self.avg_pickup_time) if self.avg_pickup_time else 0,
            
            # 评分体系
            'store_score': float(self.store_score) if self.store_score else 0,
            'satisfaction_score': float(self.satisfaction_score) if self.satisfaction_score else 0,
            'taste_score': float(self.taste_score) if self.taste_score else 0,
            'packaging_score': float(self.packaging_score) if self.packaging_score else 0,
            
            # 近60日评价
            'good_rate_60d': float(self.good_rate_60d) if self.good_rate_60d else 0,
            'good_count_60d': self.good_count_60d,
            'medium_rate_60d': float(self.medium_rate_60d) if self.medium_rate_60d else 0,
            'medium_count_60d': self.medium_count_60d,
            'bad_rate_60d': float(self.bad_rate_60d) if self.bad_rate_60d else 0,
            'bad_count_60d': self.bad_count_60d,
            'quality_rate_60d': float(self.quality_rate_60d) if self.quality_rate_60d else 0,
            'quality_count_60d': self.quality_count_60d,
            'review_rate_60d': float(self.review_rate_60d) if self.review_rate_60d else 0,
            'review_count_60d': self.review_count_60d,
            'bad_reply_rate_60d': float(self.bad_reply_rate_60d) if self.bad_reply_rate_60d else 0,
            
            # 近30日评价
            'good_rate_30d': float(self.good_rate_30d) if self.good_rate_30d else 0,
            'good_count_30d': self.good_count_30d,
            'medium_rate_30d': float(self.medium_rate_30d) if self.medium_rate_30d else 0,
            'medium_count_30d': self.medium_count_30d,
            'bad_rate_30d': float(self.bad_rate_30d) if self.bad_rate_30d else 0,
            'bad_count_30d': self.bad_count_30d,
            'quality_rate_30d': float(self.quality_rate_30d) if self.quality_rate_30d else 0,
            'quality_count_30d': self.quality_count_30d,
            'review_rate_30d': float(self.review_rate_30d) if self.review_rate_30d else 0,
            'review_count_30d': self.review_count_30d,
            'bad_reply_rate_30d': float(self.bad_reply_rate_30d) if self.bad_reply_rate_30d else 0,
        }


class ElemeOrderData(db.Model):
    """饿了么订单明细数据表（来自食亨收银系统）"""
    __tablename__ = 'eleme_order_data'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    
    # 基础信息
    store_name = db.Column(db.String(200), nullable=False, index=True)
    store_id = db.Column(db.String(50), index=True)
    
    # 订单核心信息
    order_id = db.Column(db.String(100), unique=True, nullable=False, index=True)  # 订单号：唯一索引，去重依据
    order_status = db.Column(db.String(50))  # 订单状态：已完成、已退款等
    order_time = db.Column(db.DateTime, index=True)  # 下单时间
    order_type = db.Column(db.String(20))  # 预约/即时单
    
    # 出餐信息
    cooking_time = db.Column(db.Integer)  # 出餐时间（分钟）
    cooking_type = db.Column(db.String(50))  # 出餐类型：正常、延迟等
    
    # 订单详情
    guest_count = db.Column(db.Integer, default=0)  # 就餐人数
    product_info = db.Column(db.Text)  # 商品信息（长文本，后续需要正则拆解）
    pickup_number = db.Column(db.String(50))  # 取餐号
    order_note = db.Column(db.Text)  # 订单备注
    refund_reason = db.Column(db.String(200))  # 退款原因（可为空）
    
    # 财务信息（核心指标）
    estimated_income = db.Column(db.Numeric(12, 2), default=0)  # 预计收入（元）- 核心指标
    platform_service_fee = db.Column(db.Numeric(10, 2), default=0)  # 平台服务费
    other_fee = db.Column(db.Numeric(10, 2), default=0)  # 其他费用
    delivery_fee = db.Column(db.Numeric(10, 2), default=0)  # 配送费
    discount_name = db.Column(db.String(500))  # 优惠名称
    package_fee = db.Column(db.Numeric(10, 2), default=0)  # 餐盒费
    
    # 元数据
    import_batch_id = db.Column(db.String(50), index=True)  # 导入批次ID
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    
    def to_dict(self):
        """转换为字典"""
        return {
            'id': self.id,
            'store_name': self.store_name,
            'store_id': self.store_id,
            'order_id': self.order_id,
            'order_status': self.order_status,
            'order_time': self.order_time.isoformat() if self.order_time else None,
            'order_type': self.order_type,
            'cooking_time': self.cooking_time,
            'cooking_type': self.cooking_type,
            'guest_count': self.guest_count,
            'product_info': self.product_info,
            'pickup_number': self.pickup_number,
            'order_note': self.order_note,
            'refund_reason': self.refund_reason,
            'estimated_income': float(self.estimated_income) if self.estimated_income else 0,
            'platform_service_fee': float(self.platform_service_fee) if self.platform_service_fee else 0,
            'other_fee': float(self.other_fee) if self.other_fee else 0,
            'delivery_fee': float(self.delivery_fee) if self.delivery_fee else 0,
            'discount_name': self.discount_name,
            'package_fee': float(self.package_fee) if self.package_fee else 0,
        }


class ElemeOrderElemeData(db.Model):
    """饿了么订单数据表（直接从饿了么后台导出）"""
    __tablename__ = 'eleme_order_eleme_data'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    
    # 基础信息（4列）
    data_date = db.Column(db.Date, nullable=False, index=True)  # 日期
    store_name = db.Column(db.String(200), index=True)  # 门店名称
    order_id = db.Column(db.String(100), nullable=False, index=True)  # 订单单号
    product_info = db.Column(db.Text)  # 商品信息（包含套餐内所有小项目，用于正则拆解）
    
    # 元数据
    import_batch_id = db.Column(db.String(50), index=True)  # 导入批次ID
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    
    def to_dict(self):
        """转换为字典"""
        return {
            'id': self.id,
            'data_date': self.data_date.isoformat() if self.data_date else None,
            'store_name': self.store_name,
            'order_id': self.order_id,
            'product_info': self.product_info,
        }


class ElemeProductData(db.Model):
    """饿了么商品数据表"""
    __tablename__ = 'eleme_product_data'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    
    # 基础信息
    data_date = db.Column(db.Date, nullable=False, index=True)  # 日期
    city = db.Column(db.String(50), index=True)  # 城市名称
    store_name = db.Column(db.String(200), nullable=False, index=True)  # 门店名称
    store_id = db.Column(db.String(50), index=True)  # 门店编号
    product_name = db.Column(db.String(200), nullable=False, index=True)  # 商品名称
    
    # 商品属性（布尔类型字段）
    is_new_product = db.Column(db.String(10))  # 是否新品
    is_signature = db.Column(db.String(10))  # 是否招牌
    is_combo = db.Column(db.String(10))  # 是否套餐
    is_ingredient = db.Column(db.String(10))  # 是否配料
    is_sold_out = db.Column(db.String(10))  # 是否售罄
    
    # 销售数据
    sales_amount = db.Column(db.Numeric(12, 2), default=0)  # 销售额（元）
    sales_volume = db.Column(db.Integer, default=0)  # 销量
    order_user_count = db.Column(db.Integer, default=0)  # 下单人数
    order_count = db.Column(db.Integer, default=0)  # 带来订单数
    order_transaction_amount = db.Column(db.Numeric(12, 2), default=0)  # 订单交易额（元）
    
    # 复购数据
    repurchase_30d_users = db.Column(db.Integer, default=0)  # 近30日复购人数
    repurchase_30d_rate = db.Column(db.Numeric(5, 2))  # 近30日复购率（%）
    
    # 新客数据
    new_customer_count = db.Column(db.Integer, default=0)  # 新客人数
    new_customer_ratio = db.Column(db.Numeric(5, 2))  # 新客占比（%）
    
    # 用户行为数据
    exposure_users = db.Column(db.Integer, default=0)  # 曝光人数
    click_users = db.Column(db.Integer, default=0)  # 点击人数
    add_to_cart_users = db.Column(db.Integer, default=0)  # 加购人数
    add_to_cart_rate = db.Column(db.Numeric(5, 2))  # 加购率（%）
    like_count = db.Column(db.Integer, default=0)  # 点赞数
    
    # 元数据
    import_batch_id = db.Column(db.String(50), index=True)  # 导入批次ID
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    
    def to_dict(self):
        """转换为字典（包含所有24个字段）"""
        return {
            'id': self.id,
            # 基础信息
            'data_date': self.data_date.isoformat() if self.data_date else None,
            'city': self.city,
            'store_name': self.store_name,
            'store_id': self.store_id,
            'product_name': self.product_name,
            
            # 商品属性
            'is_new_product': self.is_new_product,
            'is_signature': self.is_signature,
            'is_combo': self.is_combo,
            'is_ingredient': self.is_ingredient,
            'is_sold_out': self.is_sold_out,
            
            # 销售数据
            'sales_amount': float(self.sales_amount) if self.sales_amount else 0,
            'sales_volume': self.sales_volume,
            'order_user_count': self.order_user_count,
            'order_count': self.order_count,
            'order_transaction_amount': float(self.order_transaction_amount) if self.order_transaction_amount else 0,
            
            # 复购数据
            'repurchase_30d_users': self.repurchase_30d_users,
            'repurchase_30d_rate': float(self.repurchase_30d_rate) if self.repurchase_30d_rate else 0,
            
            # 新客数据
            'new_customer_count': self.new_customer_count,
            'new_customer_ratio': float(self.new_customer_ratio) if self.new_customer_ratio else 0,
            
            # 用户行为数据
            'exposure_users': self.exposure_users,
            'click_users': self.click_users,
            'add_to_cart_users': self.add_to_cart_users,
            'add_to_cart_rate': float(self.add_to_cart_rate) if self.add_to_cart_rate else 0,
            'like_count': self.like_count,
        }


class ElemeReviewData(db.Model):
    """饿了么评价数据表"""
    __tablename__ = 'eleme_review_data'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    
    # 基础信息
    data_date = db.Column(db.Date, nullable=False, index=True)  # 日期
    store_id = db.Column(db.String(50), index=True)  # 门店ID
    store_name = db.Column(db.String(200), nullable=False, index=True)  # 门店名称
    city = db.Column(db.String(50), index=True)  # 城市名称
    
    # 订单与评价信息
    order_id = db.Column(db.String(100), index=True)  # 订单ID（允许重复，一个订单可能多次导出）
    review_time = db.Column(db.DateTime, index=True)  # 评价时间
    
    # 评分数据（1-5分制）
    overall_score = db.Column(db.Numeric(3, 1))  # 总体评分
    taste_score = db.Column(db.Numeric(3, 1))  # 味道评分
    packaging_score = db.Column(db.Numeric(3, 1))  # 包装评分
    delivery_score = db.Column(db.Numeric(3, 1))  # 配送评分
    
    # 评价内容
    review_content = db.Column(db.Text)  # 评价内容（长文本）
    reply_content = db.Column(db.Text)  # 回复内容（长文本）
    
    # 商品反馈
    liked_products = db.Column(db.Text)  # 点赞商品（可能是商品列表）
    disliked_products = db.Column(db.Text)  # 点踩商品（可能是商品列表）
    
    # 状态字段
    is_appeal_success = db.Column(db.String(10))  # 是否申诉成功（是/否）
    is_counted_in_score = db.Column(db.String(10))  # 是否计入总分（是/否）
    is_visible_to_customer = db.Column(db.String(10))  # 顾客是否会看到（是/否）
    reply_method = db.Column(db.String(50))  # 回评方式
    
    # 订单详情
    order_details = db.Column(db.Text)  # 订单详情（长文本）
    
    # 元数据
    import_batch_id = db.Column(db.String(50), index=True)  # 导入批次ID
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    
    def to_dict(self):
        """转换为字典（包含所有19个字段）"""
        return {
            'id': self.id,
            # 基础信息
            'data_date': self.data_date.isoformat() if self.data_date else None,
            'store_id': self.store_id,
            'store_name': self.store_name,
            'city': self.city,
            
            # 订单与评价信息
            'order_id': self.order_id,
            'review_time': self.review_time.isoformat() if self.review_time else None,
            
            # 评分数据
            'overall_score': float(self.overall_score) if self.overall_score else 0,
            'taste_score': float(self.taste_score) if self.taste_score else 0,
            'packaging_score': float(self.packaging_score) if self.packaging_score else 0,
            'delivery_score': float(self.delivery_score) if self.delivery_score else 0,
            
            # 评价内容
            'review_content': self.review_content,
            'reply_content': self.reply_content,
            
            # 商品反馈
            'liked_products': self.liked_products,
            'disliked_products': self.disliked_products,
            
            # 状态字段
            'is_appeal_success': self.is_appeal_success,
            'is_counted_in_score': self.is_counted_in_score,
            'is_visible_to_customer': self.is_visible_to_customer,
            'reply_method': self.reply_method,
            
            # 订单详情
            'order_details': self.order_details,
        }


class ElemeGrowthData(db.Model):
    """饿了么商家成长数据表"""
    __tablename__ = 'eleme_growth_data'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    
    # 基础信息
    data_date = db.Column(db.Date, nullable=False, index=True)  # 日期
    store_name = db.Column(db.String(200), nullable=False, index=True)  # 门店名称
    store_id = db.Column(db.String(50), index=True)  # 门店ID
    province = db.Column(db.String(50), index=True)  # 省份
    city = db.Column(db.String(50), index=True)  # 城市名称
    district = db.Column(db.String(50))  # 区县名称
    chain_name = db.Column(db.String(200))  # 顶级连锁名称
    address = db.Column(db.Text)  # 地址
    
    # 店铺评级
    l_level = db.Column(db.String(50))  # L等级分布
    store_score = db.Column(db.Numeric(10, 2))  # 店铺分
    
    # 近7日高峰营业时长
    peak_hours_7d_current = db.Column(db.Numeric(10, 2))  # 当前值
    peak_hours_7d_target = db.Column(db.Numeric(10, 2))  # 目标值
    peak_hours_7d_score = db.Column(db.Numeric(10, 2))  # 得分
    peak_hours_7d_weight = db.Column(db.Numeric(10, 2))  # 权重
    
    # 近7日营业时长
    business_hours_7d_current = db.Column(db.Numeric(10, 2))
    business_hours_7d_target = db.Column(db.Numeric(10, 2))
    business_hours_7d_score = db.Column(db.Numeric(10, 2))
    business_hours_7d_weight = db.Column(db.Numeric(10, 2))
    
    # 昨日店装丰富度
    store_decoration_current = db.Column(db.Numeric(10, 2))
    store_decoration_target = db.Column(db.Numeric(10, 2))
    store_decoration_score = db.Column(db.Numeric(10, 2))
    store_decoration_weight = db.Column(db.Numeric(10, 2))
    
    # 昨日最低起送价
    min_delivery_price_current = db.Column(db.Numeric(10, 2))
    min_delivery_price_target = db.Column(db.Numeric(10, 2))
    min_delivery_price_score = db.Column(db.Numeric(10, 2))
    min_delivery_price_weight = db.Column(db.Numeric(10, 2))
    
    # 昨日服务功能丰富度
    service_features_current = db.Column(db.Numeric(10, 2))
    service_features_target = db.Column(db.Numeric(10, 2))
    service_features_score = db.Column(db.Numeric(10, 2))
    service_features_weight = db.Column(db.Numeric(10, 2))
    
    # 昨日有效活动丰富度
    promotion_richness_current = db.Column(db.Numeric(10, 2))
    promotion_richness_target = db.Column(db.Numeric(10, 2))
    promotion_richness_score = db.Column(db.Numeric(10, 2))
    promotion_richness_weight = db.Column(db.Numeric(10, 2))
    
    # 近7日差评回复率
    negative_reply_rate_7d_current = db.Column(db.Numeric(10, 2))
    negative_reply_rate_7d_target = db.Column(db.Numeric(10, 2))
    negative_reply_rate_7d_score = db.Column(db.Numeric(10, 2))
    negative_reply_rate_7d_weight = db.Column(db.Numeric(10, 2))
    
    # 昨日商家评分
    merchant_rating_current = db.Column(db.Numeric(10, 2))
    merchant_rating_target = db.Column(db.Numeric(10, 2))
    merchant_rating_score = db.Column(db.Numeric(10, 2))
    merchant_rating_weight = db.Column(db.Numeric(10, 2))
    
    # 近7日在线联系回复率
    online_reply_rate_7d_current = db.Column(db.Numeric(10, 2))
    online_reply_rate_7d_target = db.Column(db.Numeric(10, 2))
    online_reply_rate_7d_score = db.Column(db.Numeric(10, 2))
    online_reply_rate_7d_weight = db.Column(db.Numeric(10, 2))
    
    # 昨日优质商品率
    quality_product_rate_current = db.Column(db.Numeric(10, 2))
    quality_product_rate_target = db.Column(db.Numeric(10, 2))
    quality_product_rate_score = db.Column(db.Numeric(10, 2))
    quality_product_rate_weight = db.Column(db.Numeric(10, 2))
    
    # 昨日菜单丰富度
    menu_richness_current = db.Column(db.Numeric(10, 2))
    menu_richness_target = db.Column(db.Numeric(10, 2))
    menu_richness_score = db.Column(db.Numeric(10, 2))
    menu_richness_weight = db.Column(db.Numeric(10, 2))
    
    # 商责取消率
    merchant_cancel_rate_current = db.Column(db.Numeric(10, 2))
    merchant_cancel_rate_target = db.Column(db.Numeric(10, 2))
    merchant_cancel_rate_score = db.Column(db.Numeric(10, 2))
    merchant_cancel_rate_weight = db.Column(db.Numeric(10, 2))
    
    # 近7日出餐完成上报率
    meal_report_rate_7d_current = db.Column(db.Numeric(10, 2))
    meal_report_rate_7d_target = db.Column(db.Numeric(10, 2))
    meal_report_rate_7d_score = db.Column(db.Numeric(10, 2))
    
    # 元数据
    import_batch_id = db.Column(db.String(50), index=True)  # 导入批次ID
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    
    def to_dict(self):
        """转换为字典（包含所有61个字段）"""
        return {
            'id': self.id,
            # 基础信息
            'data_date': self.data_date.isoformat() if self.data_date else None,
            'store_name': self.store_name,
            'store_id': self.store_id,
            'province': self.province,
            'city': self.city,
            'district': self.district,
            'chain_name': self.chain_name,
            'address': self.address,
            
            # 店铺评级
            'l_level': self.l_level,
            'store_score': float(self.store_score) if self.store_score else 0,
            
            # 近7日高峰营业时长
            'peak_hours_7d_current': float(self.peak_hours_7d_current) if self.peak_hours_7d_current else 0,
            'peak_hours_7d_target': float(self.peak_hours_7d_target) if self.peak_hours_7d_target else 0,
            'peak_hours_7d_score': float(self.peak_hours_7d_score) if self.peak_hours_7d_score else 0,
            'peak_hours_7d_weight': float(self.peak_hours_7d_weight) if self.peak_hours_7d_weight else 0,
            
            # 近7日营业时长
            'business_hours_7d_current': float(self.business_hours_7d_current) if self.business_hours_7d_current else 0,
            'business_hours_7d_target': float(self.business_hours_7d_target) if self.business_hours_7d_target else 0,
            'business_hours_7d_score': float(self.business_hours_7d_score) if self.business_hours_7d_score else 0,
            'business_hours_7d_weight': float(self.business_hours_7d_weight) if self.business_hours_7d_weight else 0,
            
            # 昨日店装丰富度
            'store_decoration_current': float(self.store_decoration_current) if self.store_decoration_current else 0,
            'store_decoration_target': float(self.store_decoration_target) if self.store_decoration_target else 0,
            'store_decoration_score': float(self.store_decoration_score) if self.store_decoration_score else 0,
            'store_decoration_weight': float(self.store_decoration_weight) if self.store_decoration_weight else 0,
            
            # 昨日最低起送价
            'min_delivery_price_current': float(self.min_delivery_price_current) if self.min_delivery_price_current else 0,
            'min_delivery_price_target': float(self.min_delivery_price_target) if self.min_delivery_price_target else 0,
            'min_delivery_price_score': float(self.min_delivery_price_score) if self.min_delivery_price_score else 0,
            'min_delivery_price_weight': float(self.min_delivery_price_weight) if self.min_delivery_price_weight else 0,
            
            # 昨日服务功能丰富度
            'service_features_current': float(self.service_features_current) if self.service_features_current else 0,
            'service_features_target': float(self.service_features_target) if self.service_features_target else 0,
            'service_features_score': float(self.service_features_score) if self.service_features_score else 0,
            'service_features_weight': float(self.service_features_weight) if self.service_features_weight else 0,
            
            # 昨日有效活动丰富度
            'promotion_richness_current': float(self.promotion_richness_current) if self.promotion_richness_current else 0,
            'promotion_richness_target': float(self.promotion_richness_target) if self.promotion_richness_target else 0,
            'promotion_richness_score': float(self.promotion_richness_score) if self.promotion_richness_score else 0,
            'promotion_richness_weight': float(self.promotion_richness_weight) if self.promotion_richness_weight else 0,
            
            # 近7日差评回复率
            'negative_reply_rate_7d_current': float(self.negative_reply_rate_7d_current) if self.negative_reply_rate_7d_current else 0,
            'negative_reply_rate_7d_target': float(self.negative_reply_rate_7d_target) if self.negative_reply_rate_7d_target else 0,
            'negative_reply_rate_7d_score': float(self.negative_reply_rate_7d_score) if self.negative_reply_rate_7d_score else 0,
            'negative_reply_rate_7d_weight': float(self.negative_reply_rate_7d_weight) if self.negative_reply_rate_7d_weight else 0,
            
            # 昨日商家评分
            'merchant_rating_current': float(self.merchant_rating_current) if self.merchant_rating_current else 0,
            'merchant_rating_target': float(self.merchant_rating_target) if self.merchant_rating_target else 0,
            'merchant_rating_score': float(self.merchant_rating_score) if self.merchant_rating_score else 0,
            'merchant_rating_weight': float(self.merchant_rating_weight) if self.merchant_rating_weight else 0,
            
            # 近7日在线联系回复率
            'online_reply_rate_7d_current': float(self.online_reply_rate_7d_current) if self.online_reply_rate_7d_current else 0,
            'online_reply_rate_7d_target': float(self.online_reply_rate_7d_target) if self.online_reply_rate_7d_target else 0,
            'online_reply_rate_7d_score': float(self.online_reply_rate_7d_score) if self.online_reply_rate_7d_score else 0,
            'online_reply_rate_7d_weight': float(self.online_reply_rate_7d_weight) if self.online_reply_rate_7d_weight else 0,
            
            # 昨日优质商品率
            'quality_product_rate_current': float(self.quality_product_rate_current) if self.quality_product_rate_current else 0,
            'quality_product_rate_target': float(self.quality_product_rate_target) if self.quality_product_rate_target else 0,
            'quality_product_rate_score': float(self.quality_product_rate_score) if self.quality_product_rate_score else 0,
            'quality_product_rate_weight': float(self.quality_product_rate_weight) if self.quality_product_rate_weight else 0,
            
            # 昨日菜单丰富度
            'menu_richness_current': float(self.menu_richness_current) if self.menu_richness_current else 0,
            'menu_richness_target': float(self.menu_richness_target) if self.menu_richness_target else 0,
            'menu_richness_score': float(self.menu_richness_score) if self.menu_richness_score else 0,
            'menu_richness_weight': float(self.menu_richness_weight) if self.menu_richness_weight else 0,
            
            # 商责取消率
            'merchant_cancel_rate_current': float(self.merchant_cancel_rate_current) if self.merchant_cancel_rate_current else 0,
            'merchant_cancel_rate_target': float(self.merchant_cancel_rate_target) if self.merchant_cancel_rate_target else 0,
            'merchant_cancel_rate_score': float(self.merchant_cancel_rate_score) if self.merchant_cancel_rate_score else 0,
            'merchant_cancel_rate_weight': float(self.merchant_cancel_rate_weight) if self.merchant_cancel_rate_weight else 0,
            
            # 近7日出餐完成上报率
            'meal_report_rate_7d_current': float(self.meal_report_rate_7d_current) if self.meal_report_rate_7d_current else 0,
            'meal_report_rate_7d_target': float(self.meal_report_rate_7d_target) if self.meal_report_rate_7d_target else 0,
            'meal_report_rate_7d_score': float(self.meal_report_rate_7d_score) if self.meal_report_rate_7d_score else 0,
        }


class ElemeImportLog(db.Model):
    """饿了么数据导入日志表"""
    __tablename__ = 'eleme_import_logs'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    batch_id = db.Column(db.String(50), unique=True, nullable=False)
    file_name = db.Column(db.String(200))
    data_type = db.Column(db.Enum('store', 'order_shiheng', 'order_eleme', 'product', 'review', 'growth', 'fans', name='eleme_data_type'), default='store', nullable=False)
    data_date = db.Column(db.Date, index=True)
    total_rows = db.Column(db.Integer, default=0)
    success_rows = db.Column(db.Integer, default=0)
    failed_rows = db.Column(db.Integer, default=0)
    status = db.Column(db.Enum('processing', 'completed', 'failed', name='import_status'), default='processing')
    error_message = db.Column(db.Text)
    imported_by = db.Column(db.Integer, db.ForeignKey('users.id'))
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    completed_at = db.Column(db.DateTime)
    is_deleted = db.Column(db.Boolean, default=False)
    deleted_at = db.Column(db.DateTime)
    
    # 关系
    user = db.relationship('User', backref='eleme_imports')
    
    def to_dict(self):
        """转换为字典"""
        return {
            'id': self.id,
            'batch_id': self.batch_id,
            'file_name': self.file_name,
            'data_type': self.data_type,
            'data_date': self.data_date.isoformat() if self.data_date else None,
            'total_rows': self.total_rows,
            'success_rows': self.success_rows,
            'failed_rows': self.failed_rows,
            'status': self.status,
            'error_message': self.error_message,
            'imported_by': self.imported_by,
            'importer_name': self.user.real_name if self.user else None,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'completed_at': self.completed_at.isoformat() if self.completed_at else None,
            'is_deleted': self.is_deleted,
            'deleted_at': self.deleted_at.isoformat() if self.deleted_at else None,
        }


class ElemeFieldConfig(db.Model):
    """饿了么字段配置表"""
    __tablename__ = 'eleme_field_config'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    field_name = db.Column(db.String(100), unique=True, nullable=False)
    display_name = db.Column(db.String(100), nullable=False)
    field_type = db.Column(db.String(50), default='VARCHAR')
    field_category = db.Column(db.String(50), index=True)
    is_active = db.Column(db.Boolean, default=True)
    sort_order = db.Column(db.Integer, default=0)
    description = db.Column(db.Text)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    def to_dict(self):
        """转换为字典"""
        return {
            'id': self.id,
            'field_name': self.field_name,
            'display_name': self.display_name,
            'field_type': self.field_type,
            'field_category': self.field_category,
            'is_active': self.is_active,
            'sort_order': self.sort_order,
            'description': self.description,
        }


class ElemeFansData(db.Model):
    """饿了么粉丝群数据表"""
    __tablename__ = 'eleme_fans_data'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    
    # 基础信息
    data_date = db.Column(db.Date, nullable=False, index=True)
    store_name = db.Column(db.String(200), nullable=False, index=True)
    store_id = db.Column(db.String(50), index=True)
    city = db.Column(db.String(50), index=True)
    
    # 群基础信息
    reach_threshold = db.Column(db.String(50))
    group_type = db.Column(db.String(50))
    group_count = db.Column(db.Integer, default=0)
    
    # 粉丝统计
    total_fans = db.Column(db.Integer, default=0)
    active_fans = db.Column(db.Integer, default=0)
    fan_active_rate = db.Column(db.Numeric(10, 2), default=0)
    visit_fans = db.Column(db.Integer, default=0)
    fan_visit_rate = db.Column(db.Numeric(10, 2), default=0)
    new_fans = db.Column(db.Integer, default=0)
    new_fan_ratio = db.Column(db.Numeric(10, 2), default=0)
    old_visit_fans = db.Column(db.Integer, default=0)
    old_fan_visit_rate = db.Column(db.Numeric(10, 2), default=0)
    quit_fans = db.Column(db.Integer, default=0)
    quit_fan_ratio = db.Column(db.Numeric(10, 2), default=0)
    
    # 订单统计
    group_order_count = db.Column(db.Integer, default=0)
    store_order_count = db.Column(db.Integer, default=0)
    group_order_ratio = db.Column(db.Numeric(10, 2), default=0)
    
    # 入群礼
    welcome_gift_orders = db.Column(db.Integer, default=0)
    welcome_gift_received = db.Column(db.Integer, default=0)
    
    # 群普通红包
    normal_redpack_orders = db.Column(db.Integer, default=0)
    normal_redpack_receivers = db.Column(db.Integer, default=0)
    normal_redpack_users = db.Column(db.Integer, default=0)
    normal_redpack_received = db.Column(db.Integer, default=0)
    
    # 群口令红包
    password_redpack_orders = db.Column(db.Integer, default=0)
    password_redpack_receivers = db.Column(db.Integer, default=0)
    password_redpack_users = db.Column(db.Integer, default=0)
    password_redpack_received = db.Column(db.Integer, default=0)
    
    # 群活跃度
    active_group_count = db.Column(db.Integer, default=0)
    merchant_message_group_count = db.Column(db.Integer, default=0)
    
    # 群配置
    has_welcome_gift = db.Column(db.String(50))
    send_coupon_times = db.Column(db.Integer, default=0)
    send_product_times = db.Column(db.Integer, default=0)
    has_announcement = db.Column(db.String(50))
    
    # 元数据
    import_batch_id = db.Column(db.String(50), index=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    
    def to_dict(self):
        """转换为字典（包含所有37个字段）"""
        return {
            'id': self.id,
            # 基础信息
            'data_date': self.data_date.isoformat() if self.data_date else None,
            'store_name': self.store_name,
            'store_id': self.store_id,
            'city': self.city,
            
            # 群基础信息
            'reach_threshold': self.reach_threshold,
            'group_type': self.group_type,
            'group_count': self.group_count,
            
            # 粉丝统计
            'total_fans': self.total_fans,
            'active_fans': self.active_fans,
            'fan_active_rate': float(self.fan_active_rate) if self.fan_active_rate else 0,
            'visit_fans': self.visit_fans,
            'fan_visit_rate': float(self.fan_visit_rate) if self.fan_visit_rate else 0,
            'new_fans': self.new_fans,
            'new_fan_ratio': float(self.new_fan_ratio) if self.new_fan_ratio else 0,
            'old_visit_fans': self.old_visit_fans,
            'old_fan_visit_rate': float(self.old_fan_visit_rate) if self.old_fan_visit_rate else 0,
            'quit_fans': self.quit_fans,
            'quit_fan_ratio': float(self.quit_fan_ratio) if self.quit_fan_ratio else 0,
            
            # 订单统计
            'group_order_count': self.group_order_count,
            'store_order_count': self.store_order_count,
            'group_order_ratio': float(self.group_order_ratio) if self.group_order_ratio else 0,
            
            # 入群礼
            'welcome_gift_orders': self.welcome_gift_orders,
            'welcome_gift_received': self.welcome_gift_received,
            
            # 群普通红包
            'normal_redpack_orders': self.normal_redpack_orders,
            'normal_redpack_receivers': self.normal_redpack_receivers,
            'normal_redpack_users': self.normal_redpack_users,
            'normal_redpack_received': self.normal_redpack_received,
            
            # 群口令红包
            'password_redpack_orders': self.password_redpack_orders,
            'password_redpack_receivers': self.password_redpack_receivers,
            'password_redpack_users': self.password_redpack_users,
            'password_redpack_received': self.password_redpack_received,
            
            # 群活跃度
            'active_group_count': self.active_group_count,
            'merchant_message_group_count': self.merchant_message_group_count,
            
            # 群配置
            'has_welcome_gift': self.has_welcome_gift,
            'send_coupon_times': self.send_coupon_times,
            'send_product_times': self.send_product_times,
            'has_announcement': self.has_announcement,
        }


class ElemeActiveStore(db.Model):
    """饿了么在营门店列表"""
    __tablename__ = 'eleme_active_stores'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    store_name = db.Column(db.String(200), nullable=False, unique=True, index=True, comment='门店名称（饿了么）')
    store_name_shiheng = db.Column(db.String(200), comment='门店名称（食亨）')
    is_active = db.Column(db.Boolean, default=True, comment='是否在营')
    cost_analysis_enabled = db.Column(db.Boolean, default=False, comment='是否启用成本分析')
    created_at = db.Column(db.DateTime, default=datetime.utcnow, comment='创建时间')
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, comment='更新时间')
    
    def to_dict(self):
        """转换为字典"""
        return {
            'id': self.id,
            'store_name': self.store_name,
            'store_name_shiheng': self.store_name_shiheng,
            'is_active': self.is_active,
            'cost_analysis_enabled': self.cost_analysis_enabled,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'updated_at': self.updated_at.isoformat() if self.updated_at else None,
        }


class SourceCostLibrary(db.Model):
    """源商品成本库"""
    __tablename__ = 'source_cost_library'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    source_product_name = db.Column(db.String(200), nullable=False, index=True, comment='源商品名称')
    source_product_sku = db.Column(db.String(100), nullable=False, unique=True, index=True, comment='源商品SKU')
    category = db.Column(db.String(100), comment='类别')
    cost = db.Column(db.Numeric(10, 2), nullable=False, comment='成本')
    is_deleted = db.Column(db.Boolean, default=False, comment='是否删除')
    created_at = db.Column(db.DateTime, default=datetime.utcnow, comment='创建时间')
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, comment='更新时间')
    
    def to_dict(self):
        """转换为字典"""
        return {
            'id': self.id,
            'source_product_name': self.source_product_name,
            'source_product_sku': self.source_product_sku,
            'category': self.category,
            'cost': float(self.cost) if self.cost else 0,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'updated_at': self.updated_at.isoformat() if self.updated_at else None,
        }


class ProductMapping(db.Model):
    """映射商品库"""
    __tablename__ = 'product_mapping'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    parsed_product_name = db.Column(db.String(200), nullable=False, unique=True, index=True, comment='拆解单品名称')
    source_product_name = db.Column(db.String(200), nullable=False, comment='映射源商品名称')
    source_product_sku = db.Column(db.String(100), nullable=False, comment='映射源商品SKU')
    is_deleted = db.Column(db.Boolean, default=False, comment='是否删除')
    created_at = db.Column(db.DateTime, default=datetime.utcnow, comment='创建时间')
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, comment='更新时间')
    
    def to_dict(self):
        """转换为字典"""
        return {
            'id': self.id,
            'parsed_product_name': self.parsed_product_name,
            'source_product_name': self.source_product_name,
            'source_product_sku': self.source_product_sku,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'updated_at': self.updated_at.isoformat() if self.updated_at else None,
        }

