from flask import Blueprint, request
from datetime import datetime, date
from app import db
from app.models import RoutineTaskTemplate, AutoGeneratedTask
from app.utils.auth import token_required, admin_required
from app.utils.response import success_response, error_response, paginated_response

bp = Blueprint('routine_tasks', __name__, url_prefix='/api/routine-tasks')

@bp.route('/templates', methods=['GET'])
@token_required
def get_templates(current_user):
    """获取清洁任务模板列表"""
    frequency = request.args.get('frequency')
    
    query = RoutineTaskTemplate.query.filter_by(is_active=True)
    if frequency:
        query = query.filter_by(frequency=frequency)
    
    templates = query.all()
    return success_response(
        data=[t.to_dict() for t in templates],
        message='获取模板列表成功'
    )

@bp.route('/templates', methods=['POST'])
@admin_required
def create_template(current_user):
    """创建清洁任务模板（仅管理员可操作）"""
    data = request.get_json()
    
    required_fields = ['task_name', 'frequency', 'checklist']
    for field in required_fields:
        if not data.get(field):
            return error_response(f'字段 {field} 不能为空', 400)
    
    template = RoutineTaskTemplate(
        task_name=data['task_name'],
        description=data.get('description', ''),
        frequency=data['frequency'],
        checklist_json=data['checklist'],
        is_active=data.get('is_active', True)
    )
    
    try:
        db.session.add(template)
        db.session.commit()
        return success_response(data=template.to_dict(), message='模板创建成功', code=201)
    except Exception as e:
        db.session.rollback()
        return error_response(f'创建失败: {str(e)}', 500)

@bp.route('/templates/<int:template_id>', methods=['PUT'])
@admin_required
def update_template(current_user, template_id):
    """更新清洁任务模板（仅管理员可操作）"""
    template = RoutineTaskTemplate.query.get(template_id)
    if not template:
        return error_response('模板不存在', 404)
    
    data = request.get_json()
    
    if 'task_name' in data:
        template.task_name = data['task_name']
    if 'description' in data:
        template.description = data['description']
    if 'frequency' in data:
        template.frequency = data['frequency']
    if 'checklist' in data:
        template.checklist_json = data['checklist']
    if 'is_active' in data:
        template.is_active = data['is_active']
    
    try:
        db.session.commit()
        return success_response(data=template.to_dict(), message='模板更新成功')
    except Exception as e:
        db.session.rollback()
        return error_response(f'更新失败: {str(e)}', 500)

@bp.route('/my-tasks', methods=['GET'])
@token_required
def get_my_tasks(current_user):
    """获取我的清洁任务（店长专用）"""
    if current_user['role'] != 'shop_manager':
        return error_response('仅店长可访问', 403)
    
    # 获取店长所属门店
    from app.models import User
    user = User.query.get(current_user['user_id'])
    if not user or not user.shop_id:
        return error_response('您未关联任何门店', 400)
    
    # 获取今天的日期
    today = date.today()
    task_date = request.args.get('date')
    if task_date:
        try:
            today = datetime.strptime(task_date, '%Y-%m-%d').date()
        except:
            return error_response('日期格式错误', 400)
    
    # 查询该门店当天的清洁任务
    tasks = AutoGeneratedTask.query.filter_by(
        shop_id=user.shop_id,
        due_date=today
    ).all()
    
    return success_response(
        data=[t.to_dict() for t in tasks],
        message='获取清洁任务成功'
    )

@bp.route('/<int:task_id>/complete', methods=['POST'])
@token_required
def complete_task(current_user, task_id):
    """完成清洁任务"""
    task = AutoGeneratedTask.query.get(task_id)
    if not task:
        return error_response('任务不存在', 404)
    
    data = request.get_json()
    
    task.is_completed = True
    task.completed_at = datetime.utcnow()
    task.completed_by = current_user['user_id']
    task.checklist_status = data.get('checklist_status', {})
    
    try:
        db.session.commit()
        return success_response(data=task.to_dict(), message='任务完成')
    except Exception as e:
        db.session.rollback()
        return error_response(f'操作失败: {str(e)}', 500)

